package modelo;

import java.io.IOException;
import java.sql.SQLException;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import dao.DaoMarca;
import dao.DaoRefrescos;

// Generated 17 feb. 2021 10:34:25 by Hibernate Tools 5.4.27.Final



/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name="marca")
public class Marca implements java.io.Serializable {

	@Id
	@Column(name="idmarca")
	private Integer idmarca;
	@Column(name="nombre")
	private String nombre;

	public Marca() {
	}

	public Marca(String nombre) {
		this.nombre = nombre;
	}

	public Integer getIdmarca() {
		return this.idmarca;
	}

	public void setIdmarca(Integer idmarca) {
		this.idmarca = idmarca;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}


	/**
	 * Inserta en la tabla.
	 * @throws IOException
	 * @throws SQLException
	 */
	public void insertar() throws IOException, SQLException {
		DaoMarca.insertar(this);
	}
	
	/**
	 * Actualiza los datos de la tabla.
	 * @throws IOException
	 * @throws SQLException
	 */
	public void update() throws IOException, SQLException {
		DaoMarca.update(this);
	}
	
	/**
	 *  Borrar los datos de la tabla.
	 * @throws IOException
	 * @throws SQLException
	 */
	public void delete() throws IOException, SQLException {
		DaoMarca.delete(this);
	}
	
	
	/**
	 *  Metodo que obtiene todos los elementos de la base de datos por su id.
	 * @param id
	 * @throws IOException
	 * @throws SQLException
	 */
	public void obtenerPorId(int id) throws IOException, SQLException{
		
		Marca aux = DaoMarca.obtener(idmarca);
		this.idmarca = aux.getIdmarca();
		this.nombre = aux.getNombre();
		
		
		System.out.println(this);
			
	}

	@Override
	public String toString() {
		return "Marca [idmarca=" + idmarca + ", nombre=" + nombre + "]";
	}
	
}
