package modelo;
// Generated 17 feb. 2021 10:34:25 by Hibernate Tools 5.4.27.Final

import java.io.IOException;
import java.sql.SQLException;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import dao.DaoRefrescos;
import dao.DaoSabor;

/**
 * Sabor generated by hbm2java
 */
@Entity
@Table(name="sabor")
public class Sabor implements java.io.Serializable {

	@Id
	@Column(name="idSabores")
	private Integer idSabores;
	@Column(name="nombre")
	private String nombre;

	public Sabor() {
	}

	public Sabor(String nombre) {
		this.nombre = nombre;
	}

	public Integer getIdSabores() {
		return this.idSabores;
	}

	public void setIdSabores(Integer idSabores) {
		this.idSabores = idSabores;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	
	/**
	 * Inserta en la tabla.
	 * @throws IOException
	 * @throws SQLException
	 */
	public void insertar() throws IOException, SQLException {
		DaoSabor.insertar(this);
	}
	
	/**
	 * Actualiza los datos de la tabla.
	 * @throws IOException
	 * @throws SQLException
	 */
	public void update() throws IOException, SQLException {
		DaoSabor.update(this);
	}
	
	/**
	 *  Borrar los datos de la tabla.
	 * @throws IOException
	 * @throws SQLException
	 */
	public void delete() throws IOException, SQLException {
		DaoSabor.delete(this);
	}
	
	
	/**
	 *  Metodo que obtiene todos los elementos de la base de datos por su id.
	 * @param id
	 * @throws IOException
	 * @throws SQLException
	 */
	public void obtenerPorId(int id) throws IOException, SQLException{
		
		Refresco aux = DaoRefrescos.obtener(id);
		this.idSabores = aux.getId();
		this.nombre = aux.getNombre();
		
		
		System.out.println(this);
			
	}

	@Override
	public String toString() {
		return "Sabor [idSabores=" + idSabores + ", nombre=" + nombre + "]";
	}

	
	
}
